admin:
    resource: "@AppBundle/Resources/config/routing/admin/routing.yml"
    prefix:   /

api:
    resource: "@AppBundle/Resources/config/routing/api/routing.yml"
    prefix:   /

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
